ROLES = [
    "Admin",
    "Manager",
    "Sales Rep",
    "Marketing",
    "Support",
    "Viewer",
]

PERMISSIONS = {
    "Dashboard": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "Marketing",
        "Support": "Support",
        "Viewer": "Read",
    },
    "Leads": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "Marketing",
        "Support": "Read",
        "Viewer": "Read",
    },
    "Deals / Opportunities": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "Read",
    },
    "Tasks & Activities": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "None",
        "Support": "Support",
        "Viewer": "Read",
    },
    "Campaigns": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "None",
        "Marketing": "Marketing",
        "Support": "None",
        "Viewer": "Read",
    },
    "Customers": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "Read",
        "Support": "Support",
        "Viewer": "Read",
    },
    "Geo Insights": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "None",
        "Marketing": "Read",
        "Support": "None",
        "Viewer": "Read",
    },
    "Unified Inbox": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "Self",
        "Marketing": "Marketing",
        "Support": "Support",
        "Viewer": "None",
    },
    "User Management": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "None",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "None",
    },
    "Team Management": {
        "Admin": "Full",
        "Manager": "Team",
        "Sales Rep": "None",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "None",
    },
    "Role & Permission Control": {
        "Admin": "Full",
        "Manager": "None",
        "Sales Rep": "None",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "None",
    },
    "System & API Integrations": {
        "Admin": "Full",
        "Manager": "None",
        "Sales Rep": "None",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "None",
    },
    "Theme & Widget Customization": {
        "Admin": "Full",
        "Manager": "None",
        "Sales Rep": "None",
        "Marketing": "None",
        "Support": "None",
        "Viewer": "None",
    },
}